/**
 * The unattended schedule: what runs on its own, how often, and why that often.
 *
 * Everything in this app can be run by hand, and until now everything had to be.
 * The pages paper over that — `refreshIfStale` and `ingestIfStale` refetch when
 * what they find is too old — but paying for a refresh on a page render is a
 * fallback, not a plan: it makes the first visit of the morning the slowest, and
 * it does nothing at all for the weekly insight, which is deliberately never
 * generated by a render (see `insights/view.ts`).
 *
 * Two decisions are worth stating, because both could reasonably have gone the
 * other way.
 *
 * **The cadences are derived from the staleness windows, not chosen next to
 * them.** `market.refresh` runs every `QUOTE_TTL_MS` and `news.refresh` every
 * `NEWS_TTL_MS`, imported rather than retyped. A schedule that drifts from the
 * TTL it exists to stay ahead of is worse than no schedule: it looks like
 * coverage while leaving a window where every visitor still pays for the fetch.
 * Change a TTL and the installed job changes with it.
 *
 * **A job is a chain of steps, not a moment in the day.** The weekly insight
 * needs fresh bars and fresh headlines to reason over. Expressing that as three
 * separate jobs timed to fall in the right order is a guess about how long a
 * backfill takes; expressing it as one job whose steps run `&&` is a guarantee.
 * It costs one redundant backfill a week and removes the entire class of "the
 * insight ran before the data landed".
 *
 * This module is pure: it renders text. `scripts/schedule.ts` is the part that
 * touches the machine.
 */
import { QUOTE_TTL_MS } from "@/lib/markets/refresh";
import { NEWS_TTL_MS } from "@/lib/news/ingest";

/**
 * launchd label prefix, and the reverse-DNS-ish namespace the jobs live in.
 *
 * Deliberately not derived from `BRAND`. Renaming the product is meant to be a
 * one-line change; it must not silently orphan five agents already installed in
 * `~/Library/LaunchAgents` under the old name, which is what a brand-derived
 * label would do.
 */
export const LABEL_PREFIX = "local.psxpm";

/** launchd and cron agree: 0 is Sunday, 1 is Monday. */
export const MONDAY = 1;

export type Cadence =
  | { readonly kind: "interval"; readonly seconds: number }
  | { readonly kind: "daily"; readonly hour: number; readonly minute: number }
  | {
      readonly kind: "weekly";
      readonly weekday: number;
      readonly hour: number;
      readonly minute: number;
    };

export interface Job {
  /** Stable id. Becomes the launchd label and the log filename, so never rename lightly. */
  readonly id: string;
  readonly summary: string;
  /** Why this cadence and not another. Printed by `npm run schedule`. */
  readonly why: string;
  /** npm scripts, in order. Each must succeed for the next to run. */
  readonly steps: readonly string[];
  readonly cadence: Cadence;
}

/**
 * Every job, in the order a reader should meet them: quotes, then the daily
 * close, then news, then the weekly write-up that depends on all three.
 */
export const JOBS: readonly Job[] = [
  {
    id: "market-refresh",
    summary: "Refresh every tracked quote",
    why: `matches QUOTE_TTL_MS (${QUOTE_TTL_MS / 60_000}m), so a page render never has to fetch`,
    steps: ["market:refresh"],
    cadence: { kind: "interval", seconds: QUOTE_TTL_MS / 1000 },
  },
  {
    id: "market-backfill",
    summary: "Pull daily bars for every tracked asset",
    why: "a daily close changes once a day; 06:00 is after every tracked market has closed",
    steps: ["market:backfill"],
    cadence: { kind: "daily", hour: 6, minute: 0 },
  },
  {
    id: "news-refresh",
    summary: "Sweep every market feed and look up unusual movers",
    why: `matches NEWS_TTL_MS (${NEWS_TTL_MS / 60_000}m)`,
    steps: ["news:refresh"],
    cadence: { kind: "interval", seconds: NEWS_TTL_MS / 1000 },
  },
  {
    id: "news-prune",
    summary: "Drop headlines older than 90 days, then refresh",
    why: "pruning is something a refresh does when asked, so this is the ordinary job with a flag",
    steps: ["news:refresh -- --prune=90"],
    cadence: { kind: "daily", hour: 6, minute: 20 },
  },
  {
    id: "insights-weekly",
    summary: "Backfill, refresh news, then generate the week's insights",
    why: "an insight reasons over a full week; Monday 08:00 is the first moment that week is complete",
    // The chain is the point. See the module comment.
    steps: ["market:backfill", "news:refresh", "insights:generate -- --prune=26"],
    cadence: { kind: "weekly", weekday: MONDAY, hour: 8, minute: 0 },
  },
];

export function jobById(id: string): Job | undefined {
  return JOBS.find((j) => j.id === id);
}

export function labelFor(job: Job): string {
  return `${LABEL_PREFIX}.${job.id}`;
}

export function logPathFor(job: Job, logDir: string): string {
  return `${logDir}/${job.id}.log`;
}

/* ------------------------------------------------------------------ rendering */

/**
 * Wrap for `sh -c`. Single quotes take everything literally, so the only
 * character needing care is the single quote itself.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * The one command a job runs.
 *
 * `&&` between steps, so a failed backfill stops the chain rather than letting
 * the insight be written from data that never arrived.
 */
export function commandFor(job: Job, repoDir: string): string {
  const steps = job.steps.map((s) => `npm run ${s}`).join(" && ");
  return `cd ${shellQuote(repoDir)} && ${steps}`;
}

export function xmlEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

const WEEKDAY_NAME = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function describeCadence(cadence: Cadence): string {
  switch (cadence.kind) {
    case "interval": {
      const m = cadence.seconds / 60;
      return m >= 1 && Number.isInteger(m)
        ? `every ${m} minute${m === 1 ? "" : "s"}`
        : `every ${cadence.seconds}s`;
    }
    case "daily":
      return `daily at ${pad2(cadence.hour)}:${pad2(cadence.minute)}`;
    case "weekly":
      return `${WEEKDAY_NAME[cadence.weekday] ?? `weekday ${cadence.weekday}`} at ${pad2(cadence.hour)}:${pad2(cadence.minute)}`;
  }
}

export interface RenderOptions {
  /** Absolute path to the repo. */
  readonly repoDir: string;
  /** Absolute path to write `.log` files into. */
  readonly logDir: string;
  /**
   * Login shell used to run the command.
   *
   * Run with `-lc`, not `-c`. A launchd agent inherits a bare `PATH`
   * (`/usr/bin:/bin:/usr/sbin:/sbin`), which has no `npm` under nvm, Homebrew or
   * any other user-level install — the job fails instantly with "command not
   * found" and the only trace is an empty log. A login shell reads the profile
   * that put node on the path in the first place.
   */
  readonly shell?: string;
}

const DEFAULT_SHELL = "/bin/zsh";

/**
 * A launchd agent, ready to write to `~/Library/LaunchAgents`.
 *
 * launchd rather than cron, and the reason is the weekly job. cron on a laptop
 * simply skips whatever was due while the lid was shut and never mentions it, so
 * a Monday-morning insight is missed by any Monday morning that starts late.
 * launchd runs a missed `StartCalendarInterval` job when the machine wakes.
 *
 * launchd also runs one instance per label at a time, which is what keeps a slow
 * five-minute quote refresh from stacking up behind itself against rate-limited
 * providers.
 */
export function plistFor(job: Job, opts: RenderOptions): string {
  const { repoDir, logDir, shell = DEFAULT_SHELL } = opts;
  const label = labelFor(job);
  const log = logPathFor(job, logDir);
  const lines = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `  <key>Label</key>`,
    `  <string>${xmlEscape(label)}</string>`,
    `  <key>ProgramArguments</key>`,
    `  <array>`,
    `    <string>${xmlEscape(shell)}</string>`,
    `    <string>-lc</string>`,
    `    <string>${xmlEscape(commandFor(job, repoDir))}</string>`,
    `  </array>`,
    `  <key>WorkingDirectory</key>`,
    `  <string>${xmlEscape(repoDir)}</string>`,
    `  <key>StandardOutPath</key>`,
    `  <string>${xmlEscape(log)}</string>`,
    `  <key>StandardErrorPath</key>`,
    `  <string>${xmlEscape(log)}</string>`,
    `  <key>ProcessType</key>`,
    `  <string>Background</string>`,
    `  <key>RunAtLoad</key>`,
    // An interval job should start counting from now, not from now plus an
    // interval. A calendar job must not fire every time you log in.
    `  <${job.cadence.kind === "interval" ? "true" : "false"}/>`,
    ...cadenceKeys(job.cadence),
    `</dict>`,
    `</plist>`,
    ``,
  ];
  return lines.join("\n");
}

function cadenceKeys(cadence: Cadence): string[] {
  if (cadence.kind === "interval") {
    return [`  <key>StartInterval</key>`, `  <integer>${cadence.seconds}</integer>`];
  }
  const entries = [
    `  <key>StartCalendarInterval</key>`,
    `  <dict>`,
    ...(cadence.kind === "weekly"
      ? [`    <key>Weekday</key>`, `    <integer>${cadence.weekday}</integer>`]
      : []),
    `    <key>Hour</key>`,
    `    <integer>${cadence.hour}</integer>`,
    `    <key>Minute</key>`,
    `    <integer>${cadence.minute}</integer>`,
    `  </dict>`,
  ];
  return entries;
}

/**
 * The same job as a crontab line, for a machine that is not a Mac.
 *
 * Returns `null` when cron cannot express the cadence honestly rather than
 * rounding it: cron's finest grain is a minute, and a step field only means
 * "every n minutes" when n divides the hour. Nothing here currently hits that,
 * and the check script keeps it that way.
 *
 * Read this as documentation of the same schedule, not as a second supported
 * path — a cron box does not run a job it slept through, which is the reason
 * launchd is the installed one.
 */
export function crontabFor(job: Job, opts: RenderOptions): string | null {
  const spec = cronSpec(job.cadence);
  if (!spec) return null;
  const log = logPathFor(job, opts.logDir);
  const command = commandFor(job, opts.repoDir);
  return `${spec} ${command} >> ${log} 2>&1`;
}

function cronSpec(cadence: Cadence): string | null {
  if (cadence.kind === "interval") {
    const minutes = cadence.seconds / 60;
    if (!Number.isInteger(minutes) || minutes < 1) return null;
    if (minutes === 1) return "* * * * *";
    if (minutes >= 60 || 60 % minutes !== 0) return null;
    return `*/${minutes} * * * *`;
  }
  const day = cadence.kind === "weekly" ? String(cadence.weekday) : "*";
  return `${cadence.minute} ${cadence.hour} * * ${day}`;
}
